---
- name: Converge | Apply roles to consulserver
  hosts: consulserver
  roles:
    - rsyslog
    - consul_role

- name: Converge | Apply rsyslog role to consulagent
  hosts: consulagent
  roles:
    - rsyslog

- name: Converge | Run tasks on consulagent
  hosts: consulagent
  gather_facts: true
  tasks:
  - name: Converge | Block to apply role with not http or script parameters
    block:
    - name: Converge | Try to apply role with not http or script parameters
      ansible.builtin.include_role:
        name: idealista.consul_role
      vars:
        consul_services_register:
        - name: node exporter http
          port: 9100
    rescue:
      - name: Converge | Set fact role_error_params
        ansible.builtin.set_fact:
          role_error_params: true
    always:
    - name: Converge | Fail if no error raised
      ansible.builtin.fail:
        msg: "An error should've been raised by the role"
      when: role_error_params is not defined

  - name: Converge | Block to apply role with bad configured webservice
    block:
      - name: Converge | Try to apply role with bad configured webservice
        ansible.builtin.include_role:
          name: idealista.consul_role
        vars:
          consul_services_register:
          - name: node exporter http
            port: 9100
            http: "http://localhost:14/randomurl"
            interval: "60s"
    rescue:
    - name: Converge | Set fact role_error_webservice
      ansible.builtin.set_fact:
        role_error_webservice: true
    always:
    - name: Converge | Fail if no error raised
      ansible.builtin.fail:
        msg: "An error should've been raised by the role"
      when: role_error_webservice is not defined

  - name: Converge | Block to apply role with bad configured service
    block:
      - name: Converge | Try to apply role with bad configured service
        ansible.builtin.include_role:
          name: idealista.consul_role
        vars:
          consul_services_register:
          - name: node exporter http
            script: "command_dont_exists"
            interval: "60s"
    rescue:
      - name: Converge | Set fact role_error_service
        ansible.builtin.set_fact:
          role_error_service: true
    always:
    - name: Converge | Fail if no error raised
      ansible.builtin.fail:
        msg: "An error should've been raised by the role"
      when: role_error_service is not defined

  - name: Converge | Block to apply role with bad configured service with no sanity check
    block:
      - name: Converge | Try to apply role with bad configured service with no sanity check
        ansible.builtin.include_role:
          name: idealista.consul_role
        vars:
          consul_service_sanity_healthcheck: false
          consul_services_register:
          - name: node exporter http
            script: "command_dont_exists"
            interval: "60s"
    rescue:
      - name: Converge | Set fact role_error
        ansible.builtin.set_fact:
          role_error: true
    always:
    - name: Converge | Fail if no error raised
      ansible.builtin.fail:
        msg: "An error should've been raised by the role"
      when: role_error is defined
