---

- name: Side Effect | Consul
  hosts: consulagent
  gather_facts: true
  vars:
    consul_uninstall: true
  roles:
    - role: "{{ 'idealista.consul_role' if (ansible_version.string  is version('2.17.9', '>=')) else 'consul_role' }}"
