---
- name: Verify
  hosts: all
  vars:
    goss_version: v0.3.11
    goss_arch: amd64
    goss_dst: /usr/local/bin/goss
    goss_sha256sum: 7a751c102abac61fd8dff45f87f36c3732cb5158e1414ab78e6877864fc2f7a4
    goss_url:
      "https://github.com/aelsabbahy/goss/releases/download/\
      {{ goss_version }}/goss-linux-{{ goss_arch }}"
    goss_test_directory: /tmp
    goss_format: documentation

  tasks:
    - name: Download and install goss
      get_url:
        url: "{{ goss_url }}"
        dest: "{{ goss_dst }}"
        mode: 0755

    - name: Copy tests to remote
      template:
        src: "{{ item }}"
        dest: "{{ goss_test_directory }}/{{ item | basename }}"
      with_fileglob:
        - "{{ playbook_dir }}/tests/test_{{ ansible_fqdn }}.yml"

    - name: Register test files
      shell: "ls {{ goss_test_directory }}/test_{{ ansible_fqdn }}.yml"
      register: test_files

    - name: Execute Goss tests
      command: "goss -g {{ item }} validate --format {{ goss_format }}"
      register: test_results
      with_items: "{{ test_files.stdout_lines }}"
      ignore_errors: true

    - name: Display details about the goss results
      debug:
        msg: "{{ item.stdout_lines }}"
      with_items: "{{ test_results.results }}"

    - name: Fail when tests fail
      fail:
        msg: "Goss failed to validate"
      when: item.rc != 0
      with_items: "{{ test_results.results }}"
