---

- name: Consul | Check Consul version
  command: consul --version
  changed_when: false
  ignore_errors: true
  register: consul_installed_version
  check_mode: no

- name: Consul | Set consul_installed_version fact
  set_fact:
    consul_installed_version: "{{ consul_installed_version }}"
