---
- name: Consul | Add acl configuration master
  ansible.builtin.template:
    src: consul.master.j2
    dest: "{{ consul_configdir }}/master.json"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0640
  notify: Restart consul
  no_log: true
  when: consul_server

- name: Consul | Add acl configuration client
  ansible.builtin.template:
    src: consul.client.j2
    dest: "{{ consul_configdir }}/client.json"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0640
  notify: Restart consul
  no_log: true
  when: consul_agent

- name: Consul | ACLs system needs to be enabled prior to apply them
  ansible.builtin.meta: flush_handlers
  when: consul_acl  # This is to avoid triggering handlers unnecessarily

- name: Consul | Install consul_acl prerequisites
  ansible.builtin.apt:
    name: "{{ consul_python_apt_required_packages }}"

- name: Consul | Install consul_acl Python prerequisites
  ansible.builtin.pip:
    name: "{{ consul_python_pip_required_packages }}"

- name: Consul | Wait for Consul to start up
  ansible.builtin.wait_for:
    port: "{{ consul_http_port }}"
    timeout: 60

- name: Consul | Create ACLs
  ansible.builtin.include_tasks: consul_acl_new.yml
  when: not consul_acl_use_legacy
  tags:
    - configure
    - acl

- name: Consul | Create ACLs (legacy)
  ansible.builtin.include_tasks: consul_acl_legacy.yml
  when: consul_acl_use_legacy
  tags:
    - configure
    - acl_legacy
