---
- name: Consul | Add acl configuration master
  template:
    src: consul.master.j2
    dest: "{{ consul_configdir }}/master.json"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0640
  notify: restart consul
  no_log: "{{ consul_no_log }}"
  when: consul_server

- name: Consul | Add acl configuration client
  template:
    src: consul.client.j2
    dest: "{{ consul_configdir }}/client.json"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0640
  notify: restart consul
  no_log: "{{ consul_no_log }}"
  when: consul_agent

- name: Consul | ACLs system needs to be enabled prior to apply them
  meta: flush_handlers
  when: consul_acl  # This is to avoid triggering handlers unnecessarily

- name: Consul | Install consul_acl prerequisites
  apt:
    name: "{{ consul_acl_required_libs }}"

- name: Consul | Install consul_acl Python prerequisites
  pip:
    name: "{{ consul_acl_python_required_packages }}"

- name: Consul | Wait for Consul to start up
  wait_for:
    port: "{{ consul_http_port }}"
    timeout: 60

- name: Consul | Create ACL
  consul_acl:
    name: "{{ item.key }}"
    token_type: "{{ item.value.token_type }}"
    token: "{{ item.value.token }}"
    rules: "{{ item.value.rules }}"
    mgmt_token: "{{ consul_acl_master_token }}"
    host: "{{ consul_server_nodes | first }}"
  notify: restart consul
  with_dict: "{{ consul_acl_configuration_list }}"
  no_log: "{{ consul_no_log }}"
