---

- name: Consul | Create ACL (legacy)
  consul_acl:
    name: "{{ item.key }}"
    token_type: "{{ item.value.token_type }}"
    token: "{{ item.value.token }}"
    rules: "{{ item.value.rules }}"
    mgmt_token: "{{ consul_acl_master_token }}"
    host: "{{ consul_server_nodes | first }}"
  notify: Restart consul
  with_dict: "{{ consul_acl_configuration_list }}"
  no_log: true
  tags: [acl_legacy]
