---
- name: Consul | Install dependencies (APT)
  ansible.builtin.apt:
    pkg: "{{ consul_apt_required_packages + consul_python_apt_required_packages }}"
    update_cache: true
    cache_valid_time: 600

- name: Consul | Install Python dependencies (PIP)
  ansible.builtin.pip:
    name: "{{ consul_python_pip_required_packages }}"

- name: Consul | Ensure Consul group
  ansible.builtin.group:
    name: "{{ consul_group }}"

- name: Consul | Ensure Consul user
  ansible.builtin.user:
    name: "{{ consul_user }}"
    group: "{{ consul_group }}"
    createhome: no

- name: Consul | Ensure Consul skeleton path
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0755
  with_items:
    - "{{ consul_bindir }}"
    - "{{ consul_configdir }}"
    - "{{ consul_datadir }}"
    - "{{ consul_logdir }}"

- name: Consul | Download and extract Consul
  ansible.builtin.unarchive:
    src: "{{ consul_url }}"
    dest: "{{ consul_bindir }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    remote_src: yes
  notify: Restart consul

- name: Consul | Link binary
  ansible.builtin.file:
    src: "{{ consul_bindir }}/consul"
    dest: /usr/bin/consul
    state: link
