---
- name: Consul | Download and extract Consul
  unarchive:
    src: "{{ consul_url }}"
    dest: "{{ consul_bindir }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    remote_src: yes
  notify: restart consul

- name: Consul | Link binary
  file:
    src: "{{ consul_bindir }}/consul"
    dest: /usr/bin/consul
    state: link
