---
- name: Consul | Install dependencies
  apt:
    pkg: "{{ consul_required_libs }}"
    update_cache: true
    cache_valid_time: 600

- name: Consul | Install virtualenv dependencies
  apt:
    pkg: "{{ consul_virtualenv_required_libs }}"
    update_cache: true
    cache_valid_time: 600
  when: consul_python_virtualenv

- name: Consul | Create python virtualenv
  command: "{{ consul_python_bin }} -m virtualenv {{ consul_python_virtualenv_path }}"
  changed_when: false
  when: consul_python_virtualenv

- name: Consul | Install python dependencies
  pip:
    name: "{{ consul_required_python_libs }}"
    virtualenv: "{{ consul_python_virtualenv_path if consul_python_virtualenv else omit }}"

- name: Consul | Ensure Consul group
  group:
    name: "{{ consul_group }}"

- name: Consul | Ensure Consul user
  user:
    name: "{{ consul_user }}"
    group: "{{ consul_group }}"
    createhome: no

- name: Consul | Ensure Consul skeleton path
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0755
  with_items:
    - "{{ consul_bindir }}"
    - "{{ consul_configdir }}"
    - "{{ consul_datadir }}"
    - "{{ consul_logdir }}"

- name: Consul | Download and extract Consul
  unarchive:
    src: "{{ consul_url }}"
    dest: "{{ consul_bindir }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    remote_src: yes
  notify: Restart consul

- name: Consul | Link binary
  file:
    src: "{{ consul_bindir }}/consul"
    dest: /usr/bin/consul
    state: link
