---
- name: Consul | Gather  OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  tags:
    - check
    - install
    - configure

- name: Consul | Define consul_required_libs
  set_fact:
    consul_required_libs: "{{ __consul_required_libs }}"
  when: consul_required_libs is not defined
  tags:
    - check
    - install
    - configure

- name: Consul | Check
  import_tasks: check.yml
  tags:
    - check

- name: Consul | Install
  import_tasks: install.yml
  tags:
    - install
  when: consul_installed_version.rc != 0 or consul_force_install or consul_version not in consul_installed_version.stdout

- name: Consul | Configure
  import_tasks: config.yml
  tags:
    - configure

- name: Consul | Service
  import_tasks: service.yml
  tags:
    - service

- name: Consul | Consul ACL
  import_tasks: consul_acl.yml
  when: consul_acl
  tags:
    - configure
    - acl

- name: Consul | Consul services registration
  import_tasks: consul_services_registration.yml
  when: consul_agent_services and consul_agent
  tags:
    - configure
    - services
