---
consul_agent: true
# for goss testing
consul_server: false
consul_agent_services: true
consul_ui: true
consul_enable_script_check: true

consul_services_register:
  - name: node exporter http
    port: 9100
    http: "http://localhost:9100/metrics"
    interval: "60s"
    timeout: "30s"
  - name: node exporter script
    script: "pidof node_exporter"
    interval: "60s"
    timeout: 1
