---
- hosts: consulagent
  roles:
    - node_exporter

- hosts: consul
  gather_facts: true
  roles:
    - rsyslog
    - consul_role
  post_tasks:
    - name: Install net-tools for testing purposes
      apt:
        name: net-tools
