---

- name: Converge | Node exporter
  hosts: consulagent
  roles:
    - node_exporter

- name: Converge | Consul
  hosts: consul
  gather_facts: true
  roles:
    - rsyslog
    - consul_role
  post_tasks:
    - name: Install net-tools for testing purposes
      ansible.builtin.apt:
        name: net-tools
