# Molecule managed

{% if item.registry is defined %}
FROM --platform={{ item.platform | default('amd64') }} {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM --platform={{ item.platform | default('amd64') }} {{ item.image }}
{% endif %}

# install minimal packages for debian slim images
{% if 'stretch' in item.image %}
RUN rm /etc/apt/sources.list.d/* || true
RUN echo "deb http://archive.debian.org/debian/ {{ distro }} main contrib non-free" > /etc/apt/sources.list && \
    echo "deb-src http://archive.debian.org/debian/ {{ distro }} main contrib non-free" >> /etc/apt/sources.list && \
    echo "deb http://archive.debian.org/debian-security {{ distro }}/updates main contrib non-free" >> /etc/apt/sources.list && \
    echo "deb-src http://archive.debian.org/debian-security {{ distro }}/updates main contrib non-free" >> /etc/apt/sources.list && \
    echo "deb http://archive.debian.org/debian/ {{ distro }}-backports main contrib non-free" >> /etc/apt/sources.list && \
    echo "deb-src http://archive.debian.org/debian/ {{ distro }}-backports main contrib non-free" >> /etc/apt/sources.list
RUN apt-get update
RUN apt-get install -y python
{% else %}
RUN apt-get update
RUN apt-get install -y python3
RUN apt-get install -y  sudo bash ca-certificates iproute2 systemd systemd-sysv procps
{% endif %}

RUN apt-get clean

# https://github.com/moby/moby/issues/28614#issuecomment-310581026
STOPSIGNAL SIGRTMIN+3
RUN systemctl set-default multi-user.target
